services:
  postgres:
    image: postgres:16-alpine
    container_name: scraper-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scraper
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./sql/prs.sql:/docker-entrypoint-initdb.d/010-prs.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scraper"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  pg-data: {}
